# Agent 06: User-Guided Recipe Costing

This notebook will interactively guide you through the process of exploring, cleaning, and costing your recipe data. I will ask questions at each step, and you will provide the direction.

In [ ]:
# Phase 0: Setup and Environment Configuration
%load_ext autoreload
%autoreload 2

import sys
import os
import pandas as pd

# --- Setup Project Environment ---
# Correctly navigate up three levels to the main project root
project_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir, os.pardir, os.pardir))
src_path = os.path.join(project_root, 'src')

if src_path not in sys.path:
    sys.path.append(src_path)

# --- Define Key Paths ---
# The data paths are inside the recipe_analyzer/AGENTS directory
data_path = os.path.join(project_root, 'recipe_analyzer', 'AGENTS', 'data')
input_path = os.path.join(data_path, 'input')
output_path = os.path.join(data_path, 'output')
RECIPE_FILE = 'RECETARIO_Lleno.xlsx'
recipe_file_path = os.path.join(input_path, RECIPE_FILE)

print("✅ Setup complete. Environment configured and paths are set.")
print(f"   - Project Root: {project_root}")
print(f"   - Input File Path: {recipe_file_path}")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
✅ Setup complete. Environment configured and paths are set.
   - Project Root: c:\Users\Admin\Desktop\02. PROGRAMACION\01. TRAINING EXCERSISES\01. Proyecto Costeo Facturas_v3
   - Input File Path: c:\Users\Admin\Desktop\02. PROGRAMACION\01. TRAINING EXCERSISES\01. Proyecto Costeo Facturas_v3\recipe_analyzer\AGENTS\data\input\RECETARIO_Lleno.xlsx

### Phase 1: Data Exploration

**Step 1.1: List All Sheets in the Excel File**

I will now inspect the Excel file and list all the sheets it contains.

In [ ]:
try:
    xls = pd.ExcelFile(recipe_file_path)
    sheet_names = xls.sheet_names
    print("✅ Successfully inspected the Excel file. Here are the sheets it contains:")
    for name in sheet_names:
        print(f"   - {name}")
except FileNotFoundError:
    print(f"❌ ERROR: The recipe file was not found at the expected path: {recipe_file_path}")
except Exception as e:
    print(f"❌ ERROR: An unexpected error occurred: {e}")

✅ Successfully inspected the Excel file. Here are the sheets it contains:
   - ISNTRUCCIONES
   - Recetas
   - SKUs_Aprobados
   - Inventario
   - PRODUCTOS VENDIDOS

### User Guidance (Step 1.1)

You have identified the following sheets as relevant for our task:
*   `Recetas`
*   `Inventario`

I will now proceed to analyze these two sheets.

### Step 1.2: Analyze 'Recetas' and 'Inventario' Sheets

I will now load the two sheets you identified as relevant into separate DataFrames. I will display a preview and the technical information for each one. Please review them and prepare to explain the important columns.

In [5]:
try:
    # --- Analyze 'Recetas' Sheet ---
    print("--- Analyzing 'Recetas' Sheet ---")
    recetas_df = pd.read_excel(recipe_file_path, sheet_name='Recetas')
    print("📋 First 10 rows of 'Recetas':")
    display(recetas_df.head(10))
    print("\\n📋 Info for 'Recetas':")
    recetas_df.info()

    print("\\n" + "="*50 + "\\n") # Separator

    # --- Analyze 'Inventario' Sheet ---
    print("--- Analyzing 'Inventario' Sheet ---")
    inventario_df = pd.read_excel(recipe_file_path, sheet_name='Inventario')
    print("📋 First 10 rows of 'Inventario':")
    display(inventario_df.head(10))
    print("\\n📋 Info for 'Inventario':")
    inventario_df.info()

except Exception as e:
    print(f"❌ ERROR: An unexpected error occurred: {e}")

--- Analyzing 'Recetas' Sheet ---
📋 First 10 rows of 'Recetas':

c:\Users\Admin\Desktop\02. PROGRAMACION\01. TRAINING EXCERSISES\01. Proyecto Costeo Facturas_v3\venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,HIERARCHY_TYPE,PRODUCTO,INGREDIENTES,CANTIDAD,MEDIDA,SKU_MATCH,sku_key,unit_price,supplier_name,last_purchase_date,standardized_unit,units_per_package
0,Sub-recipe,MASA PIZZA (17pz),HARINA SIR LANCELOT,2475,G,HARINA HI-GLUTEN SIR LANCELOT KA 3052 LB,sku_b808480d_50221002_harina_hi_gluten_sir_lan...,929.200000,ABASTECEDORA DE ALIMENTOS Y EMBUTIDOS VALLE HE...,2025-09-05 11:34:58,Kilogramos,22.60
1,Sub-recipe,MASA PIZZA (17pz),HARINA SIR LANCELOT,2475,G,HARINA HI-GLUTEN SIR LANCELOT KA 3052 LB,sku_71a083bd_50221002_harina_higluten_sir_lanc...,929.200000,ABASTECEDORA DE ALIMENTOS Y EMBUTIDOS VALLE HE...,2025-08-16 12:43:02,Kilogramos,22.70
2,Sub-recipe,MASA PIZZA (17pz),HARINA SIR GALLAHAD,2475,G,HARINA ARTISAN SIR GALAHAD KA 3028 50LB,sku_0356f92a_50221300_harina_artisan_sir_galah...,526.400000,ABASTECEDORA DE ALIMENTOS Y EMBUTIDOS VALLE HE...,2025-09-05 11:34:58,Kilogramos,22.67
3,Sub-recipe,MASA PIZZA (17pz),HARINA CENTENO,550,G,HARINA DE CENTENO DARK BAY STATE 18.14KG,sku_181f6523_50221300_harina_de_centeno_dark_b...,692.200000,ABASTECEDORA DE ALIMENTOS Y EMBUTIDOS VALLE HE...,2025-08-06 15:00:42,Kilogramos,18.14
4,Sub-recipe,MASA PIZZA (17pz),MASA MADRE,1370,G,NO_MATCH_FOUND,NaN,NaN,NaN,NaT,NaN,NaN
5,Sub-recipe,MASA PIZZA (17pz),AGUA,3645,G,AGUA TONICA,sku_2d7c943f_50202306_agua_tonica,16.379310,VANESSA IVON PIÑUELAS VERDUGO,2025-08-09 12:33:16,Piezas,12.00
6,Sub-recipe,MASA PIZZA (17pz),AGUA,3645,G,AGUA TONICA,sku_ffcedf08_50202301_agua_tonica,11.206897,VANESSA IVON PIÑUELAS VERDUGO,2025-07-04 11:11:33,Piezas,1.00
7,Sub-recipe,MASA PIZZA (17pz),ACEITE DE OLIVA,450,G,NO_MATCH_FOUND,NaN,NaN,NaN,NaT,NaN,NaN
8,Sub-recipe,MASA PIZZA (17pz),SAL,165,G,SAL,sku_de658b47_50171551_sal,25.000000,VANESSA IVON PIÑUELAS VERDUGO,2025-07-30 05:51:10,Kilogramos,1.00
9,Sub-recipe,MASA PIZZA (17pz),HARINA SIR LANCELOT,3150,G,HARINA HI-GLUTEN SIR LANCELOT KA 3052 LB,sku_b808480d_50221002_harina_hi_gluten_sir_lan...,929.200000,ABASTECEDORA DE ALIMENTOS Y EMBUTIDOS VALLE HE...,2025-09-05 11:34:58,Kilogramos,22.60

\n📋 Info for 'Recetas':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   HIERARCHY_TYPE      846 non-null    object
 1   PRODUCTO            846 non-null    object
 2   INGREDIENTES        846 non-null    object
 3   CANTIDAD            782 non-null    object
 4   MEDIDA              816 non-null    object
 5   SKU_MATCH           846 non-null    object
 6   sku_key             600 non-null    object
 7   unit_price          600 non-null    float64
 8   supplier_name       600 non-null    object
 9   last_purchase_date  600 non-null    datetime64[ns]
 10  standardized_unit   600 non-null    object
 11  units_per_package   600 non-null    float64
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 79.4+ KB
\n==================================================\n
--- Analyzing 'Inventario' Sheet ---
📋 First 10 rows of 'Inventario':

c:\Users\Admin\Desktop\02. PROGRAMACION\01. TRAINING EXCERSISES\01. Proyecto Costeo Facturas_v3\venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Area,Producto,Receta / Sub Receta / SKU,UNIDAD DE MEDIDA,Unnamed: 4
0,Linea Pizza,Parmesano,SKU,KG,NaN
1,Linea Pizza,Albahaca,SKU,KG,Si es Receta o Sub Receta Copiar y Pegar el no...
2,Linea Pizza,Arugula,SKU,KG,NaN
3,Linea Pizza,Chile Quebrado,SKU,KG,NaN
4,Linea Pizza,Pepperoncini,SKU,KG,NaN
5,Linea Pizza,Pepperoni,SKU,KG,NaN
6,Linea Pizza,Salami,SKU,KG,NaN
7,Linea Pizza,Queso Mozzarella,SKU,KG,NaN
8,Linea Pizza,Miel Picante,SUB RECETA,KG,NaN
9,Linea Pizza,Salsa De Pizza,SUB RECETA,KG,NaN

\n📋 Info for 'Inventario':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Area                       244 non-null    object
 1   Producto                   244 non-null    object
 2   Receta / Sub Receta / SKU  244 non-null    object
 3   UNIDAD DE MEDIDA           244 non-null    object
 4   Unnamed: 4                 1 non-null      object
dtypes: object(5)
memory usage: 9.7+ KB

### Phase 2: Interactive Data Cleaning

**User Guidance (Column Definitions):**

You have provided the following definitions for the key columns:
*   `HIERARCHY_TYPE`: Defines if the item is a `Recipe`, `Sub-recipe`, etc.
*   `PRODUCTO`: The name of the recipe or sub-recipe.
*   `INGREDIENTES`: The generic name of an ingredient.
*   `SKU_MATCH`: The specific, purchasable SKU that maps to the generic ingredient. This is the key we will use to find the price.
*   `CANTIDAD`: The quantity of the ingredient needed.
*   `MEDIDA`: The unit of measure for the quantity.

**Goal:** Clean and standardize the `Recetas` and `Inventario` sheets based on these rules.

**Action A: Select and Rename Columns in `Recetas` Sheet**

First, I will select only the columns we need and rename them to be more code-friendly.

In [ ]:
# Define the columns we want to keep and their new names
columns_to_keep = {
    'HIERARCHY_TYPE': 'hierarchy_type',
    'PRODUCTO': 'recipe_name',
    'INGREDIENTES': 'ingredient_name',
    'CANTIDAD': 'quantity',
    'MEDIDA': 'unit',
    'SKU_MATCH': 'sku_match'
}

# Select and rename the columns
try:
    cleaned_recetas_df = recetas_df[list(columns_to_keep.keys())].copy()
    cleaned_recetas_df.rename(columns=columns_to_keep, inplace=True)

    print("✅ Successfully selected and renamed columns.")
    print("📋 Preview of the cleaned 'Recetas' DataFrame:")
    display(cleaned_recetas_df.head())
    
except KeyError as e:
    print(f"❌ ERROR: A specified column was not found in the DataFrame. Please check the column names. Details: {e}")
except Exception as e:
    print(f"❌ ERROR: An unexpected error occurred: {e}")

✅ Successfully selected and renamed columns.
📋 Preview of the cleaned 'Recetas' DataFrame:

,hierarchy_type,recipe_name,ingredient_name,quantity,unit,sku_match
0,Sub-recipe,MASA PIZZA (17pz),HARINA SIR LANCELOT,2475,G,HARINA HI-GLUTEN SIR LANCELOT KA 3052 LB
1,Sub-recipe,MASA PIZZA (17pz),HARINA SIR LANCELOT,2475,G,HARINA HI-GLUTEN SIR LANCELOT KA 3052 LB
2,Sub-recipe,MASA PIZZA (17pz),HARINA SIR GALLAHAD,2475,G,HARINA ARTISAN SIR GALAHAD KA 3028 50LB
3,Sub-recipe,MASA PIZZA (17pz),HARINA CENTENO,550,G,HARINA DE CENTENO DARK BAY STATE 18.14KG
4,Sub-recipe,MASA PIZZA (17pz),MASA MADRE,1370,G,NO_MATCH_FOUND

**Action B: Clean the `quantity` Column**

Next, I will convert the `quantity` column to a numeric data type. I will then find and display any rows where the quantity could not be converted, so you can decide how we should handle them.

In [ ]:
# Convert 'quantity' to numeric, coercing errors to NaN
cleaned_recetas_df['quantity'] = pd.to_numeric(cleaned_recetas_df['quantity'], errors='coerce')

# Find rows where quantity could not be converted
invalid_quantity_rows = cleaned_recetas_df[cleaned_recetas_df['quantity'].isna()]

if invalid_quantity_rows.empty:
    print("✅ All quantity values were successfully converted to a numeric type.")
else:
    print(f"⚠️ Found {len(invalid_quantity_rows)} rows where 'quantity' could not be converted to a number.")
    print("   Please review these rows:")
    display(invalid_quantity_rows)

print("\\n📋 Technical info for the DataFrame after conversion:")
cleaned_recetas_df.info()

⚠️ Found 93 rows where 'quantity' could not be converted to a number.
   Please review these rows:

,hierarchy_type,recipe_name,ingredient_name,quantity,unit,sku_match
41,Sub-recipe,HARINA PARA ESTIRAR PIZZA,INGREDIENTES,NaN,MEDIDA,NO_MATCH_FOUND
57,Sub-recipe,PEPERONATA,PIMIENTO MORRON ROJO,NaN,NaN,MORRON ROJO
83,Sub-recipe,AJO CONFIT,AJO,NaN,NaN,AJO
84,Sub-recipe,AJO CONFIT,ACEITE OLIVA POMACE,NaN,NaN,ACEITE OLIVA POMACE GENCO PLAST 3.78 LT
85,Sub-recipe,AJO CONFIT,ACEITE OLIVA POMACE,NaN,NaN,ACEITE OLIVA POMACE GENCO PLAST 3.78 LT
...,...,...,...,...,...,...
798,Recipe,FRUTA CON GRANOLA Y YOGURT,FRESA,NaN,G,FRESA
803,Recipe,AVOTOAST,SAL,NaN,G,SAL
804,Recipe,AVOTOAST,PIMIENTA,NaN,G,PIMIENTA ENTERA
805,Recipe,AVOTOAST,CHILE ANCHO,NaN,G,NO_MATCH_FOUND
806,Recipe,AVOTOAST,AJONJOLÍ NEGRO,NaN,G,AJONJOLI

\n📋 Technical info for the DataFrame after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   hierarchy_type   846 non-null    object
 1   recipe_name      846 non-null    object
 2   ingredient_name  846 non-null    object
 3   quantity         753 non-null    float64
 4   unit             816 non-null    object
 5   sku_match        846 non-null    object
dtypes: float64(1), object(5)
memory usage: 39.8+ KB

**Insight into Missing Quantities**

To help decide how to handle the rows with missing quantities, I will now analyze the rest of the dataset. For each ingredient with a missing quantity, I will calculate the average quantity used for that same ingredient in other recipes. This will provide context for our decision.

In [ ]:
# Calculate the average quantity for each ingredient across the entire dataset
avg_quantities = cleaned_recetas_df.groupby('ingredient_name')['quantity'].mean().to_dict()

# Map these average quantities to the rows with invalid quantities
invalid_quantity_rows['avg_quantity_elsewhere'] = invalid_quantity_rows['ingredient_name'].map(avg_quantities)

print("📋 Context for ingredients with missing quantities:")
display(invalid_quantity_rows[['recipe_name', 'ingredient_name', 'avg_quantity_elsewhere']])

📋 Context for ingredients with missing quantities:

C:\Users\Admin\AppData\Local\Temp\ipykernel_6580\3745066602.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  invalid_quantity_rows['avg_quantity_elsewhere'] = invalid_quantity_rows['ingredient_name'].map(avg_quantities)

                    recipe_name       ingredient_name  avg_quantity_elsewhere
41    HARINA PARA ESTIRAR PIZZA          INGREDIENTES                     NaN
57                  PEPERONATA   PIMIENTO MORRON ROJO                     NaN
83                   AJO CONFIT                   AJO              144.666667
84                   AJO CONFIT   ACEITE OLIVA POMACE                     NaN
85                   AJO CONFIT   ACEITE OLIVA POMACE                     NaN
..                          ...                   ...                     ...
798  FRUTA CON GRANOLA Y YOGURT                FRESA                      NaN
803                    AVOTOAST                  SAL               102.250000
804                    AVOTOAST             PIMIENTA                 2.000000
805                    AVOTOAST           CHILE ANCHO              300.000000
806                    AVOTOAST       AJONJOLÍ NEGRO                 3.000000

[93 rows x 3 columns]

**User Guidance: Handling Missing Quantities**

You have directed me to handle the 93 rows with missing quantities by filling them with `0`. This is a safe approach that keeps the ingredient record in the recipe without affecting the cost calculation. The long-term plan is to build a dedicated "Recipe Builder" tool to properly manage and fill in these gaps.

I will now apply this rule.

In [ ]:
# Fill NaN values in the 'quantity' column with 0
cleaned_recetas_df['quantity'].fillna(0, inplace=True)

# Verify that there are no more NaN values in the 'quantity' column
nan_in_quantity = cleaned_recetas_df['quantity'].isna().sum()

if nan_in_quantity == 0:
    print("✅ Successfully filled all missing quantity values with 0.")
    print("   The 'quantity' column is now clean.")
else:
    print(f"⚠️ Verification failed. There are still {nan_in_quantity} missing values in the 'quantity' column.")

print("\\n📋 Technical info for the DataFrame after filling missing values:")
cleaned_recetas_df.info()

✅ Successfully filled all missing quantity values with 0.
   The 'quantity' column is now clean.
\n📋 Technical info for the DataFrame after filling missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   hierarchy_type   846 non-null    object
 1   recipe_name      846 non-null    object
 2   ingredient_name  846 non-null    object
 3   quantity         846 non-null    float64
 4   unit             816 non-null    object
 5   sku_match        846 non-null    object
dtypes: float64(1), object(5)
memory usage: 39.8+ KB

C:\Users\Admin\AppData\Local\Temp\ipykernel_6580\1574686465.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_recetas_df['quantity'].fillna(0, inplace=True)

**Action C: Standardize Units of Measure**

The `quantity` column is now clean. The next critical step is to standardize the `unit` column so that all ingredients are measured in one of our three target units: **Litros**, **Kilogramos**, or **Piezas**.

First, I will find and display all the unique units currently in the dataset.

In [ ]:
# Find and display all unique values in the 'unit' column
unique_units = cleaned_recetas_df['unit'].dropna().unique()

print("Found the following unique units in the data:")
for unit in unique_units:
    print(f"   - {unit}")

Found the following unique units in the data:
   - G
   - MEDIDA
   - KG
   - Kg
   - G
   - pz
   - ML
   - Pz
   - PZ
   - Kg
   - Cucharada
   - Cucharada
   - Cucharadas
   - PIZCA
   - PZ
   - K
   - COSTILLAR COMPLETO
   - RECETA
   - Litro
   - Cucharadita
   - RECETA
   - CABEZA
   - %
   -  G
   - g
   - Gg
   - H